# -*- coding: utf-8 -*-
"""Testing Ground YOLOv9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jl1ynSyZDuLNrG1N6eOA15xksYJ9wLI-
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Adjust the base directory as per your Google Drive folder structure
base_dir = '/content/drive/MyDrive/KumpulanModel'

# Model path
model_path = os.path.join(base_dir, 'best.pt')

# Image path (adjust the image file name as necessary)
image_path = os.path.join(base_dir, 'picture/wn.jpg')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/WongKinYiu/yolov9.git
# %cd yolov9
!pip install -r requirements.txt -q

!python detect.py --weights '{model_path}' --img 640 --conf 0.25 --source '{image_path}'