# -*- coding: utf-8 -*-
"""YOLOv9 TA v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1DZmV_h-WX4IAMbQUQD-WCd2TG3C72-

# How to Train YOLOv9 on a Custom Dataset
---

[![GitHub](https://badges.aleen42.com/src/github.svg)](https://github.com/WongKinYiu/yolov9)
[![arXiv](https://img.shields.io/badge/arXiv-2402.13616-b31b1b.svg)](https://arxiv.org/pdf/2402.13616.pdf)

<br>

![YOLOv9 Benchmark](https://storage.googleapis.com/com-roboflow-marketing/notebooks/examples/yolov9-benchmark.jpeg)

## Before you start

Let's make sure that we have access to GPU. We can use `nvidia-smi` command to do that. In case of any problems navigate to `Edit` -> `Notebook settings` -> `Hardware accelerator`, set it to `GPU`, and then click `Save`.
"""

!nvidia-smi

"""**NOTE:** To make it easier for us to manage datasets, images and models we create a `HOME` constant."""

import os
HOME = os.getcwd()
print(HOME)

"""## Clone and Install

**NOTE:** YOLOv9 is very new. At the moment, we recommend using a fork of the main repository. The `detect.py` script contains a bug that prevents inference. This bug is patched in the fork.
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/WongKinYiu/yolov9.git
# %cd yolov9
!pip install -r requirements.txt -q

"""**NOTE:** Let's install additional packages that will be useful later on."""

!pip install -q roboflow

"""## Imports"""

import roboflow

from IPython.display import Image

"""## Download model weights

**NOTE:** In the YOLOv9 paper, versions yolov9-s and yolov9-m are also mentioned, but the weights for these models are not yet available in the YOLOv9 repository.
"""

!mkdir -p {HOME}/weights

!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-c.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-e.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-e.pt

!ls -la {HOME}/weights

"""## Download example data"""

!mkdir -p {HOME}/data


# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9


from roboflow import Roboflow
rf = Roboflow(api_key="5dDggxfyiXKXXOiHfrDv")
project = rf.workspace("fp-pcv-z6u2a").project("detect-cl54w")
version = project.version(1)
dataset = version.download("yolov9")

"""## Train Custom Model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

!python train.py \
--batch 8 --epochs 10 --img 640 --device 0 --min-items 0 --close-mosaic 15 \
--data {dataset.location}/data.yaml \
--weights {HOME}/weights/gelan-c.pt \
--cfg models/detect/gelan-c.yaml \
--hyp hyp.scratch-high.yaml

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files

files.download('/content/yolov9/runs/train/exp/weights/best.pt')

files.download('/content/yolov9/runs/train/exp/weights/best_striped.pt')

"""## Examine Training Results

**NOTE:** By default, the results of each subsequent training sessions are saved in `{HOME}/yolov9/runs/train/`, in directories named `exp`, `exp2`, `exp3`, ... You can override this behavior by using the `--name` parameter.
"""

!ls {HOME}/yolov9/runs/train/exp/

Image(filename=f"{HOME}/yolov9/runs/train/exp/results.png", width=1000)

Image(filename=f"{HOME}/yolov9/runs/train/exp/confusion_matrix.png", width=1000)

Image(filename=f"{HOME}/yolov9/runs/train/exp/val_batch0_pred.jpg", width=1000)

"""## Validate Custom Model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

!python val.py \
--img 640 --batch 8 --conf 0.001 --iou 0.7 --device 0 \
--data {dataset.location}/data.yaml \
--weights {HOME}/yolov9/runs/train/exp/weights/best.pt

"""## Inference with Custom Model"""

!python detect.py \
--img 640 --conf 0.1 --device 0 \
--weights {HOME}/yolov9/runs/train/exp/weights/best.pt \
--source {dataset.location}/valid/images

Image(filename=f"{HOME}/yolov9/runs/val/exp/confusion_matrix.png", width=1000)

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/yolov9/runs/detect/exp/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")